title: Dayda
name: General Services Administration
description: >-
  This is a catalog of datasets organized and made more accessible from the
  General Services Administration, providing simple dowloadable CSV and JSON
  files, as well as Postman Collections you can use as part of workflows and
  other automation.
about: This is all about the entity.
source_url: 'http://example.com'
source_contact_type: general
source_phone: +1 555-555-5555
source_email: info@example.com
source_catalog: data.gov
profile_pic: 2021-01-21-204905.279111240px-US-GeneralServicesAdministration-Logo.svg.png
favicon: /assets/img/favicon.png
url: 'http://general-services-administration.dayda.org'
encoding: utf-8
paginate: 25
paginate_path: '/page:num/'
markdown: kramdown
